<?php
/**
 * Title: Erklärung zur Barrierefreiheit
 * Slug: aws/barrierefreiheit
 * Categories: aws
 * Inserter: true
 * Description: Rechtstext der Aller-Weser-Oberschule.
 */
?>
<!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Erklärung zur Barrierefreiheit</h1><!-- /wp:heading --><!-- wp:paragraph --><p>Nach § 9 des Niedersächsischen Behindertengleichstellungsgesetzes (NBGG) i. V. m. der BITV 2.0.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Geltungsbereich</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Diese Erklärung gilt für die Website <strong>obs-doerverden.de</strong> der Aller-Weser-Oberschule Dörverden.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Stand der Vereinbarkeit</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Diese Website ist mit den Anforderungen der BITV 2.0 weitgehend vereinbar. Sie wurde von Beginn an barrierearm gestaltet (ausreichende Farbkontraste, Tastaturbedienbarkeit, Textalternativen, responsives Layout, Rücksicht auf reduzierte Bewegung).</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Nicht barrierefreie Inhalte</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Derzeit sind keine Einschränkungen bekannt. Sollten künftig einzelne Inhalte (z. B. eingebundene Dokumente oder Karten) nicht vollständig barrierefrei sein, werden sie hier benannt.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Erstellung dieser Erklärung</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Diese Erklärung wurde am 28. August 2026 erstellt. Grundlage der Bewertung ist eine Selbstbewertung.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Barrieren melden — Feedback und Kontakt</h2><!-- /wp:heading --><!-- wp:group {"className":"aws-block"} --><div class="wp-block-group aws-block"><!-- wp:paragraph --><p>Aller-Weser-Oberschule Dörverden<br>Am Sünderberg 6, 27313 Dörverden<br>Telefon: 04234 1034 · E-Mail: <a href="mailto:sekretariat@schulzentrum-doerverden.de">sekretariat@schulzentrum-doerverden.de</a></p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:heading --><h2 class="wp-block-heading">Durchsetzungsverfahren</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Wenn wir Ihre Rückmeldung nicht zufriedenstellend beantworten, können Sie sich an die Schlichtungsstelle nach § 9d NBGG wenden:</p><!-- /wp:paragraph --><!-- wp:group {"className":"aws-block"} --><div class="wp-block-group aws-block"><!-- wp:paragraph --><p>Schlichtungsstelle nach § 9d NBGG<br>im Büro der Landesbeauftragten für Menschen mit Behinderungen<br>Hanna-Arendt-Platz 2, 30159 Hannover<br>Telefon: 0511 120-4010 · E-Mail: <a href="mailto:schlichtungsstelle@ms.niedersachsen.de">schlichtungsstelle@ms.niedersachsen.de</a></p><!-- /wp:paragraph --></div><!-- /wp:group -->
