<?php
/**
 * Title: Erklärung zur Barrierefreiheit
 * Slug: aws/barrierefreiheit
 * Categories: aws
 * Inserter: true
 * Description: Rechtstext-Vorlage der Aller-Weser-Oberschule (bitte pruefen/ergaenzen).
 */
?>
<!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Erklärung zur Barrierefreiheit</h1><!-- /wp:heading --><!-- wp:paragraph --><p>Nach § 9 des Niedersächsischen Behindertengleichstellungsgesetzes (NBGG) i. V. m. der BITV 2.0.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong>Entwurf.</strong> Der Stand der Barrierefreiheit wird beim Livegang geprüft; die <span class="aws-todo">markierten</span> Angaben sind dann festzulegen.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Geltungsbereich</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Diese Erklärung gilt für die Website <strong>obs-doerverden.de</strong> der Aller-Weser-Oberschule Dörverden.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Stand der Vereinbarkeit</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Diese Website ist mit den Anforderungen der BITV 2.0 <span class="aws-todo">vollständig / teilweise — beim Livegang festlegen</span> vereinbar. Die Seite wurde von Beginn an barrierearm gestaltet (Farbkontraste, Tastaturbedienbarkeit, Textalternativen, responsives Layout).</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Nicht barrierefreie Inhalte</h2><!-- /wp:heading --><!-- wp:paragraph --><p><span class="aws-todo">Sofern vorhanden hier auflisten (z. B. einzelne PDF-Dokumente, eingebettete Karten). Andernfalls: „Derzeit sind keine Einschränkungen bekannt.“</span></p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Erstellung dieser Erklärung</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Diese Erklärung wurde am <span class="aws-todo">TT.MM.JJJJ</span> erstellt. Grundlage der Bewertung ist eine <span class="aws-todo">Selbstbewertung</span>.</p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading">Barrieren melden — Feedback und Kontakt</h2><!-- /wp:heading --><!-- wp:group {"className":"aws-block"} --><div class="wp-block-group aws-block"><!-- wp:paragraph --><p>Aller-Weser-Oberschule Dörverden<br>Am Sünderberg 6, 27313 Dörverden<br>Telefon: 04234 1034 · E-Mail: <a href="mailto:sekretariat@schulzentrum-doerverden.de">sekretariat@schulzentrum-doerverden.de</a></p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:heading --><h2 class="wp-block-heading">Durchsetzungsverfahren</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Wenn wir Ihre Rückmeldung nicht zufriedenstellend beantworten, können Sie sich an die zuständige Durchsetzungs-/Schlichtungsstelle des Landes Niedersachsen wenden: <span class="aws-todo">Kontakt bitte einsetzen</span>.</p><!-- /wp:paragraph -->
