<?php
/**
 * Title: Seite: Service & Infos (Schulgemeinschaft)
 * Slug: aws/service
 * Categories: aws
 * Inserter: true
 * Description: Fertige Hub-Seite mit Kacheln für bestehende Schüler:innen und Eltern. In eine neue Seite „Service & Infos“ einfügen.
 */
?>
<!-- wp:group {"className":"aws-inner"} --><div class="wp-block-group aws-inner">
<!-- wp:group {"className":"aws-sec-head"} --><div class="wp-block-group aws-sec-head"><!-- wp:paragraph {"className":"aws-eyebrow"} --><p class="aws-eyebrow">Für unsere Schulgemeinschaft</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Service &amp; Infos</h1><!-- /wp:heading --><!-- wp:paragraph --><p>Sie sind schon bei uns? Hier finden Schülerinnen, Schüler und Eltern die wichtigsten Anlaufstellen und Unterlagen für den Schulalltag – gebündelt an einem Ort.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-grid aws-grid-3"} --><div class="wp-block-group aws-grid aws-grid-3">

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-briefcase"} --><div class="wp-block-group aws-ic aws-ic-briefcase"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Downloads &amp; Formulare</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Entschuldigung, Beurlaubung, Anträge und weitere Vordrucke zum Herunterladen.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="/formulare/">Öffnen</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-learn"} --><div class="wp-block-group aws-ic aws-ic-learn"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Materiallisten</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Benötigte Materialien je Jahrgang zum Schuljahresbeginn.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="/#material">Öffnen</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-book"} --><div class="wp-block-group aws-ic aws-ic-book"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Schulbuchausleihe</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Ausleihe der Schulbücher über IServ bzw. das Buchportal.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="/#buecher">Öffnen</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-ball"} --><div class="wp-block-group aws-ic aws-ic-ball"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">AGs &amp; Ganztag</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Das aktuelle AG-Angebot und der Ganztag (Mo–Mi).</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="/#ags">Öffnen</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-star"} --><div class="wp-block-group aws-ic aws-ic-star"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Aus dem Schulalltag</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Berichte von Projekten, Festen und Ereignissen.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="/#berichte">Öffnen</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-mail"} --><div class="wp-block-group aws-ic aws-ic-mail"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Kommunikation</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Wie Sie uns erreichen und wie wir Sie informieren – im Überblick.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="/kommunikation/">Öffnen</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-phone"} --><div class="wp-block-group aws-ic aws-ic-phone"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">IServ</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Elternbriefe, Krankmeldung und Terminvergabe für den Elternsprechtag.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost","linkTarget":"_blank","rel":"noreferrer noopener"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="https://schulzentrum-doerverden.de/iserv" target="_blank" rel="noreferrer noopener">Zu IServ</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"aws-card"} --><div class="wp-block-group aws-card"><!-- wp:group {"className":"aws-ic aws-ic-clock"} --><div class="wp-block-group aws-ic aws-ic-clock"></div><!-- /wp:group --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">WebUntis</h3><!-- /wp:heading --><!-- wp:paragraph --><p>Aktueller Stunden- und Vertretungsplan.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"aws-btn-ghost","linkTarget":"_blank","rel":"noreferrer noopener"} --><div class="wp-block-button aws-btn-ghost"><a class="wp-block-button__link wp-element-button" href="https://nessa.webuntis.com/WebUntis/?school=Aller-Weser-OS+Doerverden" target="_blank" rel="noreferrer noopener">Zu WebUntis</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

</div><!-- /wp:group -->

<!-- wp:paragraph {"className":"aws-komm-note"} --><p class="aws-komm-note">Vertrauliche Mitteilungen und persönliche Dokumente stellen wir ausschließlich geschützt über <strong>IServ</strong> bereit – nicht öffentlich auf der Website.</p><!-- /wp:paragraph -->
</div><!-- /wp:group -->
